# Generated by Django 4.0.5 on 2022-07-06 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gamemembership",
            unique_together={("player", "game", "owner", "team")},
        ),
    ]
