# Generated by Django 4.0.6 on 2022-07-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_gamemembership_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="simulator_uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
