# Generated by Django 4.0.6 on 2022-07-15 22:36

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Team = apps.get_model("api", "Team")
    for team in Team.objects.all():
        team.uuid = uuid.uuid4()
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_player_simulator_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="uuid",
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="team",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
