# Generated by Django 4.0.6 on 2022-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_team_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("PG", "Point Guard"),
                    ("SG", "Shooting Guard"),
                    ("SF", "Small Forward"),
                    ("PF", "Power Forward"),
                    ("C", "Center"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="token_id",
            field=models.IntegerField(null=True),
        ),
    ]
