# Generated by Django 4.0.6 on 2022-07-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_player_position_alter_player_token_id"),
        ("api", "0005_remove_player_w_l_player_losses_player_wins"),
    ]

    operations = []
