# Generated by Django 4.0.6 on 2022-07-22 21:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_merge_20220720_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="uuid",
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="gamemembership",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_membership",
                to="api.game",
            ),
        ),
    ]
