# Generated by Django 4.0.6 on 2022-07-22 21:06
import uuid

from django.db import migrations


def generate_uuid(apps, schema_editor):
    Game = apps.get_model("api", "Game")
    for g in Game.objects.all():
        g.uuid = uuid.uuid4()
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_game_uuid_alter_gamemembership_game"),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
    ]
