# Generated by Django 4.0.6 on 2022-07-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_game_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lineup",
        ),
    ]
