# Generated by Django 4.0.6 on 2022-07-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="nonce",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(
                db_index=True, default=None, null=True, max_length=42, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
