# Generated by Django 4.0.6 on 2022-07-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(
                db_index=True, max_length=42, null=True, unique=True
            ),
        ),
    ]
