# Generated by Django 4.0.5 on 2023-07-11 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_reveal_games_by_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_100_completed_at", models.DateTimeField(blank=True, null=True)),
                ("step_200_completed_at", models.DateTimeField(blank=True, null=True)),
                ("step_300_completed_at", models.DateTimeField(blank=True, null=True)),
                ("step_400_completed_at", models.DateTimeField(blank=True, null=True)),
                ("step_500_completed_at", models.DateTimeField(blank=True, null=True)),
                ("step_600_completed_at", models.DateTimeField(blank=True, null=True)),
                ("step_700_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The datetime at which the user has completed the entire tutorial.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="A version maps to a particular sequence of steps.",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="tutorial",
            field=models.OneToOneField(
                blank=True,
                help_text="This tracks the user's progress in the tutorial.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.tutorial",
            ),
        ),
    ]
