# Generated by Django 4.0.5 on 2023-07-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_tutorial_user_tutorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_social_sign_in_user",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has used social signin.",
                verbose_name="is_social_sign_in_user",
            ),
        ),
    ]
