# Generated by Django 4.0.5 on 2023-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_social_sign_in_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="step_800_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
