# Generated by Django 4.0.5 on 2023-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_preferred_lobby_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signup_referrer_code",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
