from io import BytesIO

import requests
from django.conf import settings
from django.utils.module_loading import import_string


def get(bucket_name, aws_access_key_id, aws_secret_access_key):
    """Gets the swoops factory client"""
    return import_string(settings.SWOOPS_FACTORY_CLIENT)(
        bucket_name, aws_access_key_id, aws_secret_access_key
    )


class SwoopsFactoryClient:
    def __init__(self, host):
        self._host = host

    def _post(self, endpoint, data={}):
        url = "https://%s/%s" % (self._host, endpoint)

        response = requests.post(url, json=data)

        return response

    def generate_frontface_card(
        self,
        three_pt_rating,
        interior_2pt_rating,
        midrange_2pt_rating,
        ft_rating,
        ast_rating,
        orb_rating,
        drb_rating,
        interior_defense_rating,
        perimeter_defense_rating,
        physicality_rating,
        longevity_rating,
        hustle_rating,
        bball_iq_rating,
        leadership_rating,
        coachability_rating,
        age,
        star_rating,
        position,
        name,
        three_pt_rating_revealed,
        interior_2pt_rating_revealed,
        midrange_2pt_rating_revealed,
        ft_rating_revealed,
        drb_rating_revealed,
        orb_rating_revealed,
        ast_rating_revealed,
        physicality_rating_revealed,
        interior_defense_rating_revealed,
        perimeter_defense_rating_revealed,
        longevity_rating_revealed,
        hustle_rating_revealed,
        bball_iq_rating_revealed,
        leadership_rating_revealed,
        coachability_rating_revealed,
        top_attribute_1,
        top_attribute_2,
        top_attribute_3,
        id,
    ):
        payload = {
            "three_pt_rating": three_pt_rating,
            "interior_2pt_rating": interior_2pt_rating,
            "midrange_2pt_rating": midrange_2pt_rating,
            "ft_rating": ft_rating,
            "ast_rating": ast_rating,
            "orb_rating": orb_rating,
            "drb_rating": drb_rating,
            "interior_defense_rating": interior_defense_rating,
            "perimeter_defense_rating": perimeter_defense_rating,
            "physicality_rating": physicality_rating,
            "longevity_rating": longevity_rating,
            "hustle_rating": hustle_rating,
            "bball_iq_rating": bball_iq_rating,
            "leadership_rating": leadership_rating,
            "coachability_rating": coachability_rating,
            "age": age,
            "star_rating": star_rating,
            "position": position,
            "name": name,
            "three_pt_rating_revealed": three_pt_rating_revealed,
            "interior_2pt_rating_revealed": interior_2pt_rating_revealed,
            "midrange_2pt_rating_revealed": midrange_2pt_rating_revealed,
            "ft_rating_revealed": ft_rating_revealed,
            "drb_rating_revealed": drb_rating_revealed,
            "orb_rating_revealed": orb_rating_revealed,
            "ast_rating_revealed": ast_rating_revealed,
            "physicality_rating_revealed": physicality_rating_revealed,
            "interior_defense_rating_revealed": interior_defense_rating_revealed,
            "perimeter_defense_rating_revealed": perimeter_defense_rating_revealed,
            "longevity_rating_revealed": longevity_rating_revealed,
            "hustle_rating_revealed": hustle_rating_revealed,
            "bball_iq_rating_revealed": bball_iq_rating_revealed,
            "leadership_rating_revealed": leadership_rating_revealed,
            "coachability_rating_revealed": coachability_rating_revealed,
            "top_attribute_1": top_attribute_1,
            "top_attribute_2": top_attribute_2,
            "top_attribute_3": top_attribute_3,
            "id": id,
        }

        endpoint = "api/createFrontCard?rename=true"
        r = self._post(endpoint, data=payload)

        return BytesIO(r.content)

    def generate_backface_card(
        self,
        three_pt_rating,
        interior_2pt_rating,
        midrange_2pt_rating,
        ft_rating,
        ast_rating,
        orb_rating,
        drb_rating,
        interior_defense_rating,
        perimeter_defense_rating,
        physicality_rating,
        longevity_rating,
        hustle_rating,
        bball_iq_rating,
        leadership_rating,
        coachability_rating,
        age,
        star_rating,
        position,
        name,
        three_pt_rating_revealed,
        interior_2pt_rating_revealed,
        midrange_2pt_rating_revealed,
        ft_rating_revealed,
        drb_rating_revealed,
        orb_rating_revealed,
        ast_rating_revealed,
        physicality_rating_revealed,
        interior_defense_rating_revealed,
        perimeter_defense_rating_revealed,
        longevity_rating_revealed,
        hustle_rating_revealed,
        bball_iq_rating_revealed,
        leadership_rating_revealed,
        coachability_rating_revealed,
        top_attribute_1,
        top_attribute_2,
        top_attribute_3,
        id,
    ):
        endpoint = "api/createBackCard?rename=true"
        payload = {
            "three_pt_rating": three_pt_rating,
            "interior_2pt_rating": interior_2pt_rating,
            "midrange_2pt_rating": midrange_2pt_rating,
            "ft_rating": ft_rating,
            "ast_rating": ast_rating,
            "orb_rating": orb_rating,
            "drb_rating": drb_rating,
            "interior_defense_rating": interior_defense_rating,
            "perimeter_defense_rating": perimeter_defense_rating,
            "physicality_rating": physicality_rating,
            "longevity_rating": longevity_rating,
            "hustle_rating": hustle_rating,
            "bball_iq_rating": bball_iq_rating,
            "leadership_rating": leadership_rating,
            "coachability_rating": coachability_rating,
            "age": age,
            "star_rating": star_rating,
            "position": position,
            "name": name,
            "three_pt_rating_revealed": three_pt_rating_revealed,
            "interior_2pt_rating_revealed": interior_2pt_rating_revealed,
            "midrange_2pt_rating_revealed": midrange_2pt_rating_revealed,
            "ft_rating_revealed": ft_rating_revealed,
            "drb_rating_revealed": drb_rating_revealed,
            "orb_rating_revealed": orb_rating_revealed,
            "ast_rating_revealed": ast_rating_revealed,
            "physicality_rating_revealed": physicality_rating_revealed,
            "interior_defense_rating_revealed": interior_defense_rating_revealed,
            "perimeter_defense_rating_revealed": perimeter_defense_rating_revealed,
            "longevity_rating_revealed": longevity_rating_revealed,
            "hustle_rating_revealed": hustle_rating_revealed,
            "bball_iq_rating_revealed": bball_iq_rating_revealed,
            "leadership_rating_revealed": leadership_rating_revealed,
            "coachability_rating_revealed": coachability_rating_revealed,
            "top_attribute_1": top_attribute_1,
            "top_attribute_2": top_attribute_2,
            "top_attribute_3": top_attribute_3,
            "id": id,
        }
        r = self._post(endpoint, data=payload)
        return BytesIO(r.content)


class SwoopsFactoryMockClient:
    def __init__(self, host):
        self._host = host

    def generate_frontface_card(
        self,
        three_pt_rating,
        interior_2pt_rating,
        midrange_2pt_rating,
        ft_rating,
        ast_rating,
        orb_rating,
        drb_rating,
        interior_defense_rating,
        perimeter_defense_rating,
        physicality_rating,
        longevity_rating,
        hustle_rating,
        bball_iq_rating,
        leadership_rating,
        coachability_rating,
        age,
        star_rating,
        position,
        name,
        three_pt_rating_revealed,
        interior_2pt_rating_revealed,
        midrange_2pt_rating_revealed,
        ft_rating_revealed,
        drb_rating_revealed,
        orb_rating_revealed,
        ast_rating_revealed,
        physicality_rating_revealed,
        interior_defense_rating_revealed,
        perimeter_defense_rating_revealed,
        longevity_rating_revealed,
        hustle_rating_revealed,
        bball_iq_rating_revealed,
        leadership_rating_revealed,
        coachability_rating_revealed,
        id,
    ):
        return bytes("MOCK-123", "utf-8")

    def generate_backface_card(
        self,
        three_pt_rating,
        interior_2pt_rating,
        midrange_2pt_rating,
        ft_rating,
        ast_rating,
        orb_rating,
        drb_rating,
        interior_defense_rating,
        perimeter_defense_rating,
        physicality_rating,
        longevity_rating,
        hustle_rating,
        bball_iq_rating,
        leadership_rating,
        coachability_rating,
        age,
        star_rating,
        position,
        name,
        three_pt_rating_revealed,
        interior_2pt_rating_revealed,
        midrange_2pt_rating_revealed,
        ft_rating_revealed,
        drb_rating_revealed,
        orb_rating_revealed,
        ast_rating_revealed,
        physicality_rating_revealed,
        interior_defense_rating_revealed,
        perimeter_defense_rating_revealed,
        longevity_rating_revealed,
        hustle_rating_revealed,
        bball_iq_rating_revealed,
        leadership_rating_revealed,
        coachability_rating_revealed,
        top_attribute_1,
        top_attribute_2,
        top_attribute_3,
        id,
    ):
        return bytes("MOCK-123", "utf-8")
