# Generated by Django 4.0.5 on 2022-10-27 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamNameChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("approved_on", models.DateTimeField(default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("reject_reason", models.TextField(blank=True)),
                (
                    "acknowledged",
                    models.CharField(
                        choices=[
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("NOT_ACKNOWLEDGED", "Not Acknowledged"),
                        ],
                        default="NOT_ACKNOWLEDGED",
                        max_length=16,
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("team_id", models.BigIntegerField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
