# Generated by Django 4.0.5 on 2022-10-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamnamechangerequest",
            name="acknowledged",
        ),
    ]
