# Generated by Django 4.0.5 on 2022-10-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0004_teamlogochangerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamlogochangerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teamlogochangerequest",
            name="approved_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="teamlogochangerequest",
            name="logo_url",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="teamnamechangerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teamnamechangerequest",
            name="approved_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="teamnamechangerequest",
            name="name",
            field=models.TextField(db_index=True),
        ),
    ]
