# Generated by Django 4.0.5 on 2022-10-31 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_alter_team_logo_url_alter_teamsnapshot_logo_url"),
        ("moderation", "0005_alter_teamlogochangerequest_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamlogochangerequest",
            name="team_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.team"
            ),
        ),
        migrations.AlterField(
            model_name="teamnamechangerequest",
            name="team_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.team"
            ),
        ),
    ]
