# Generated by Django 4.0.5 on 2022-10-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0006_alter_teamlogochangerequest_team_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamlogochangerequest",
            old_name="team_id",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="teamnamechangerequest",
            old_name="team_id",
            new_name="team",
        ),
    ]
