# Generated by Django 4.0.5 on 2022-11-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0009_rename_logo_url_teamlogochangerequest_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamlogochangerequest",
            name="path",
            field=models.CharField(max_length=256),
        ),
    ]
