# Generated by Django 4.0.5 on 2022-11-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_rename_logo_url_team_path_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0010_alter_teamlogochangerequest_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamlogochangerequest",
            old_name="approved_by",
            new_name="reviewed_by",
        ),
        migrations.RenameField(
            model_name="teamlogochangerequest",
            old_name="approved_on",
            new_name="reviewed_on",
        ),
        migrations.RenameField(
            model_name="teamnamechangerequest",
            old_name="approved_by",
            new_name="reviewed_by",
        ),
        migrations.RenameField(
            model_name="teamnamechangerequest",
            old_name="approved_on",
            new_name="reviewed_on",
        ),
        migrations.AlterField(
            model_name="teamlogochangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="teamnamechangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="PlayerNameChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_on",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("reject_reason", models.TextField(blank=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "proposed_front_naked_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "proposed_front_1500_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "proposed_front_750_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "proposed_front_375_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "proposed_back_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.player"
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
