# Generated by Django 4.0.5 on 2023-04-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "moderation",
            "0011_rename_approved_by_teamlogochangerequest_reviewed_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playernamechangerequest",
            name="proposed_front_1500_key",
        ),
        migrations.RemoveField(
            model_name="playernamechangerequest",
            name="proposed_front_375_key",
        ),
        migrations.RemoveField(
            model_name="playernamechangerequest",
            name="proposed_front_750_key",
        ),
    ]
