# Generated by Django 4.0.6 on 2022-07-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="simulation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="simulator.simulation",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="simulated",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="simulator.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playersnapshot",
            name="simulated",
            field=models.ForeignKey(
                db_constraint=False,
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="simulator.player",
            ),
            preserve_default=False,
        ),
    ]
