# Generated by Django 4.0.5 on 2022-08-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_simulation_player_simulated_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW player_team_ownership AS
            SELECT
                et.token AS token,
                et.to_address AS wallet_address,
                team.id AS team_id
                FROM eth_transfer et
            INNER JOIN (
                SELECT
                    token AS token,
                    max(block) AS max_block
                FROM eth_transfer
                GROUP BY token
            ) mbt
            ON 
                et.token = mbt.token
                AND mbt.max_block = et.block
            LEFT JOIN accounts_user owner
            ON
                owner.wallet_address = wallet_address
            LEFT JOIN game_team team
            ON
                owner.id = team.owner_id
		    """
        ),
        migrations.CreateModel(
            name="PlayerOwnership",
            fields=[
                (
                    "wallet_address",
                    models.CharField(
                        help_text="the wallet address of the token owner", max_length=64
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="player token id",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        help_text="the id of the team corresponding to the owner of the token",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "player_team_ownership",
                "managed": False,
            },
        ),
    ]
