# Generated by Django 4.0.5 on 2022-08-22 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0004_reservation_reservationsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationsnapshot",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservationsnapshot",
            name="game",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reservations",
                to="game.game",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teamsnapshot",
            name="owner",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
