# Generated by Django 4.0.5 on 2022-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_fix_player_team_ownership_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                db_index=True, help_text="The official team name.", max_length=64
            ),
        ),
    ]
