# Generated by Django 4.0.5 on 2022-10-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teamsnapshot",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
    ]
