# Generated by Django 4.0.5 on 2022-10-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_team_logo_url_teamsnapshot_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="logo_url",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="teamsnapshot",
            name="logo_url",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
