# Generated by Django 4.0.5 on 2022-10-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_team_logo_url_alter_teamsnapshot_logo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="logo_url",
            new_name="path",
        ),
        migrations.RenameField(
            model_name="teamsnapshot",
            old_name="logo_url",
            new_name="path",
        ),
    ]
