# Generated by Django 4.0.5 on 2022-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_rename_logo_url_team_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="first_named_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playersnapshot",
            name="first_named_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
