# Generated by Django 4.0.5 on 2022-11-08 16:56

from django.db import migrations, models

import game.models


def update_contest_labels(apps, schema_editor):
    Contest = apps.get_model("game", "Contest")
    for contest in Contest.objects.all():
        if contest.status == "O":
            contest.status = game.models.Contest.Status.OPEN
        elif contest.status == "C":
            contest.status = game.models.Contest.Status.COMPLETE
        elif contest.status == "I":
            contest.status = game.models.Contest.Status.IN_PROGRESS

        contest.kind = "HEAD_TO_HEAD"
        contest.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_player_first_named_on_playersnapshot_first_named_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="kind",
            field=models.CharField(
                choices=[("HEAD_TO_HEAD", "Head To Head")], max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("COMPLETE", "Complete"),
                    ("IN_PROGRESS", "In Progress"),
                ],
                default="OPEN",
                max_length=12,
            ),
        ),
        migrations.RunPython(update_contest_labels),
    ]
