# Generated by Django 4.0.5 on 2022-11-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_alter_contest_kind_alter_contest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservationsnapshot",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="path",
            field=models.CharField(
                blank=True, help_text="The official team logo", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="teamsnapshot",
            name="path",
            field=models.CharField(
                blank=True, help_text="The official team logo", max_length=256
            ),
        ),
    ]
