# Generated by Django 4.0.5 on 2022-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_reservation_deleted_reservationsnapshot_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="transaction_id",
            field=models.CharField(
                blank=True, default="", help_text="Transaction Id.", max_length=255
            ),
        ),
    ]
