# Generated by Django 4.0.5 on 2022-11-25 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0013_player_ensemble"),
        ("game", "0015_game_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="simulation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game",
                to="simulator.simulation",
            ),
        ),
    ]
