# Generated by Django 4.0.5 on 2022-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_alter_contest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("COMPLETE", "Complete"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="OPEN",
                max_length=12,
            ),
        ),
    ]
