# Generated by Django 4.0.5 on 2022-12-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0014_alter_simulation_status"),
        ("game", "0018_alter_contest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="prize_pool",
            field=models.DecimalField(
                decimal_places=10, help_text="Prize Pool", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="simulation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game",
                to="simulator.simulation",
            ),
        ),
    ]
