# Generated by Django 4.0.5 on 2022-12-02 21:46

import pgtrigger
from django.db import migrations


def uninstall_pgtriggers(apps, schema_editor):
    pgtrigger.uninstall()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_game_prize_pool_alter_game_simulation"),
    ]

    operations = [migrations.RunPython(uninstall_pgtriggers, migrations.RunPython.noop)]
