# Generated by Django 4.0.5 on 2022-12-02 21:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_player_to_teamsnapshot_fk_to_player_to_team_fk(apps, schema_editor):
    Player = apps.get_model("game", "Player")
    for player in Player.objects.all():
        if player.team:
            player.team_new_id = player.team.pgh_obj_id
            player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_auto_20221202_2146"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="team_new",
            field=models.ForeignKey(
                help_text="The current team.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.team",
            ),
        ),
        migrations.RunPython(migrate_player_to_teamsnapshot_fk_to_player_to_team_fk),
        migrations.RemoveField(
            model_name="player",
            name="team",
        ),
        migrations.RenameField(
            model_name="player", old_name="team_new", new_name="team"
        ),
        migrations.RunSQL(
            """
            truncate table game_gameplayer, game_reservation, game_game, game_contest, game_lineup, game_playernote;
            """
        ),
        migrations.RemoveField(
            model_name="playersnapshot",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="playersnapshot",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="playersnapshot",
            name="simulated",
        ),
        migrations.RemoveField(
            model_name="playersnapshot",
            name="team",
        ),
        migrations.RemoveField(
            model_name="reservationsnapshot",
            name="game",
        ),
        migrations.RemoveField(
            model_name="reservationsnapshot",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="reservationsnapshot",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="reservationsnapshot",
            name="team",
        ),
        migrations.RemoveField(
            model_name="teamsnapshot",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="teamsnapshot",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="teamsnapshot",
            name="pgh_obj",
        ),
        migrations.AlterField(
            model_name="game",
            name="lineup_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.lineup",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="lineup_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.lineup",
            ),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="player_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="player_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="player_3",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="player_4",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="player_5",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.team"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                help_text="The current team.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.team",
            ),
        ),
        migrations.AlterField(
            model_name="playernote",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.player"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.team"
            ),
        ),
        migrations.DeleteModel(
            name="LineupSnapshot",
        ),
        migrations.DeleteModel(
            name="PlayerSnapshot",
        ),
        migrations.DeleteModel(
            name="ReservationSnapshot",
        ),
        migrations.DeleteModel(
            name="TeamSnapshot",
        ),
    ]
