# Generated by Django 4.0.5 on 2022-12-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_remove_playersnapshot_pgh_context_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together=set(),
        ),
    ]
