# Generated by Django 4.0.5 on 2022-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_alter_game_lineup_1_alter_game_lineup_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="starts_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RenameField(
            model_name="contest",
            old_name="starts_at",
            new_name="played_at",
        ),
    ]
