# Generated by Django 4.0.5 on 2022-12-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_alter_contest_starts_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW player_team_ownership;
		    """
        ),
        migrations.DeleteModel(
            name="PlayerOwnership",
        ),
    ]
