# Generated by Django 4.0.5 on 2023-02-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0026_game_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlayerNote",
        ),
    ]
