# Generated by Django 4.0.5 on 2023-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0027_delete_playernote"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="revealed_to_user_1",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="revealed_to_user_2",
            field=models.BooleanField(default=True),
        ),
    ]
