# Generated by Django 4.0.5 on 2023-03-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0028_game_revealed_to_user_1_game_revealed_to_user_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["stage", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reveal", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=64)),
                (
                    "payout",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Payout",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("lineup_submission_cutoff", models.DateTimeField(null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("meta", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="contest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("HEAD_TO_HEAD", "Head To Head"),
                    ("TOURNAMENT", "Tournament"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lineup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.lineup",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tournament Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="contest",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournament",
                to="game.contest",
            ),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("HIDDEN", "Hidden"),
                            ("STAFF", "Staff"),
                            ("PUBLIC", "Public"),
                        ],
                        db_index=True,
                        default="HIDDEN",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series_entry_1",
                        to="game.tournamententry",
                    ),
                ),
                (
                    "entry_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series_entry_2",
                        to="game.tournamententry",
                    ),
                ),
                ("games", models.ManyToManyField(to="game.game")),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.round"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Series",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="round",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="game.tournament"
            ),
        ),
    ]
