# Generated by Django 4.0.5 on 2023-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0029_round_tournament_alter_contest_kind_tournamententry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="populate_entry_lineups",
            field=models.BooleanField(default=False),
        ),
    ]
