# Generated by Django 4.0.5 on 2023-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0029_round_tournament_alter_contest_kind_tournamententry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("PENDING", "Pending"),
                    ("FINISHED", "Finished"),
                    ("ERRORED", "Errored"),
                    ("TERMINAL ERROR", "Terminal Error"),
                    ("TIMED OUT", "Timed Out"),
                ],
                default="NOT STARTED",
                max_length=14,
            ),
        ),
    ]
