# Generated by Django 4.0.5 on 2023-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0030_series_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("FINISHED", "Finished"),
                    ("ERRORED", "Errored"),
                ],
                default="NOT STARTED",
                max_length=14,
            ),
        ),
    ]
