# Generated by Django 4.0.5 on 2023-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0031_tournament_lineup_reveal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="lineup_reveal_date",
            field=models.DateField(null=True),
        ),
    ]
