# Generated by Django 4.0.5 on 2023-04-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0031_alter_series_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="kind",
            field=models.CharField(
                choices=[
                    ("IN SEASON", "In Season"),
                    ("END OF SEASON", "End Of Season"),
                ],
                default="IN SEASON",
                max_length=14,
            ),
        ),
    ]
