# Generated by Django 4.0.5 on 2023-04-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0030_tournament_populate_entries"),
        ("game", "0032_alter_tournament_lineup_reveal_date"),
        ("game", "0032_tournament_kind"),
    ]

    operations = []
