# Generated by Django 4.0.5 on 2023-04-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0033_merge_20230411_1935"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
