# Generated by Django 4.0.5 on 2023-04-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0034_series_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ["order"], "verbose_name_plural": "Series"},
        ),
        # migrations.RenameField(
        #     model_name="tournament",
        #     old_name="populate_entries",
        #     new_name="populate_entry_lineups",
        # ),
        migrations.AddField(
            model_name="round",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("FINISHED", "Finished"),
                ],
                default="NOT STARTED",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="payout",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Payout",
                max_digits=20,
                null=True,
            ),
        ),
    ]
