# Generated by Django 4.0.5 on 2023-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0036_tournament_lineup_submission_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamententry",
            name="rank",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
