# Generated by Django 4.0.5 on 2023-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0037_tournamententry_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("SIMULATING GAMES", "Simulating Games"),
                    ("FINISHED", "Finished"),
                ],
                default="NOT STARTED",
                max_length=20,
            ),
        ),
    ]
