# Generated by Django 4.0.5 on 2023-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0038_alter_round_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="lineup_reveal_date",
            field=models.DateTimeField(null=True),
        ),
    ]
