# Generated by Django 4.0.5 on 2023-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0039_alter_tournament_lineup_reveal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="visibility",
        ),
        migrations.AddField(
            model_name="game",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("HIDDEN", "Hidden"),
                    ("STAFF", "Staff"),
                    ("PUBLIC", "Public"),
                ],
                db_index=True,
                default="PUBLIC",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="games",
            field=models.ManyToManyField(related_name="series", to="game.game"),
        ),
    ]
