# Generated by Django 4.0.5 on 2023-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0040_remove_series_visibility_game_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="opensea_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Opensea Price USD",
                max_digits=20,
                null=True,
            ),
        ),
    ]
