# Generated by Django 4.0.5 on 2023-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0041_player_opensea_price_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="tokens_required",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
