# Generated by Django 4.0.5 on 2023-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0043_tournamentreservation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournament",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="tournament",
            name="public_publish_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("COMPLETE", "Complete"),
                    ("IN_PROGRESS", "In Progress"),
                    ("VOIDED", "Voided"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="OPEN",
                max_length=12,
            ),
        ),
    ]
