# Generated by Django 4.0.5 on 2023-06-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0044_alter_tournament_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("HEAD_TO_HEAD", "Head To Head"),
                    ("HEAD_TO_HEAD_MATCH_MAKE", "Head To Head Match Make"),
                    ("TOURNAMENT", "Tournament"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("COMPLETE", "Complete"),
                    ("IN_PROGRESS", "In Progress"),
                    ("VOIDED", "Voided"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="OPEN",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="HeadToHeadMatchMakeQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text=(
                            "A score, between 0-1, that tells you what skill level this ",
                            "team is in. We use to match teams with like scores.",
                        )
                    ),
                ),
                (
                    "max_tokens_allowed",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "sent_to_simulator_at",
                    models.DateTimeField(
                        help_text=(
                            "The time the pairing was done and ",
                            "dispatched to the simulator (in the form of a game)",
                        ),
                        null=True,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game that the pair got put into for simulation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.game",
                    ),
                ),
                (
                    "lineup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.lineup"
                    ),
                ),
                (
                    "paired_with",
                    models.ForeignKey(
                        help_text=(
                            "This is the team the submitting team got matched with. ",
                            "Initially null.",
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="headtoheadmatchmake",
                        to="game.team",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="The submitting team. They own the attached lineup.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.team",
                    ),
                ),
            ],
        ),
    ]
