# Generated by Django 4.0.5 on 2023-06-28 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0045_alter_contest_kind_alter_contest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headtoheadmatchmakequeue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
