# Generated by Django 4.0.5 on 2023-07-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0046_headtoheadmatchmakequeue_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="reveal",
        ),
        migrations.AddField(
            model_name="tournament",
            name="visibility_at",
            field=models.DateTimeField(null=True),
        ),
    ]
