# Generated by Django 4.0.5 on 2023-07-28 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0048_tournament_finalize_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="finalize_on",
            new_name="finalized_on",
        ),
    ]
