# Generated by Django 4.0.5 on 2023-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0049_rename_finalize_on_tournament_finalized_on"),
    ]

    def populate_number_of_payouts(apps, schema_editor):
        Tournament = apps.get_model("game", "Tournament")
        for tournament in Tournament.objects.all():
            # saving automatically updates the number of payouts
            tournament.save()

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="number_of_payouts",
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_number_of_payouts),
    ]
