# Generated by Django 4.0.5 on 2023-08-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0051_migrate_number_of_payouts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_wei", models.BigIntegerField()),
                ("amount_usd", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "usd_to_eth_conversion_rate",
                    models.DecimalField(decimal_places=10, default=0, max_digits=12),
                ),
                ("to_address", models.CharField(max_length=42)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("CONFIRMED", "Confirmed"),
                            ("REPLACED", "Replaced"),
                            ("ERRORED", "Errored"),
                        ],
                        default="INITIATED",
                        max_length=10,
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=66)),
                ("nonce", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="game.team",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="tournament",
            name="finalized_on",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="TournamentPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournamentpayouts",
                        to="game.payout",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                condition=models.Q(("status__exact", "INITIATED")),
                fields=["status"],
                name="game_payout_status_partial_idx",
            ),
        ),
    ]
