# Generated by Django 4.0.5 on 2023-08-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0054_tournament_banner_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="kind",
            field=models.CharField(
                choices=[
                    ("IN SEASON", "In Season"),
                    ("END OF SEASON", "End Of Season"),
                    ("PARTNER", "Partner"),
                ],
                default="IN SEASON",
                max_length=14,
            ),
        ),
    ]
