# Generated by Django 4.0.5 on 2022-08-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="defensive_iq",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="dribbling",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="dunking",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="endurance",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="free_throw_shooting",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="jumping",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="low_post_scoring",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="offensive_iq",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="passing",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="point_jump_shot_ability",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="rebounding",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="speed",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="strength",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="three_point_shooting",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="top_attributes_1",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="top_attributes_2",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="top_attributes_3",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
