# Generated by Django 4.0.5 on 2022-09-12 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0003_remove_player_position_player_position_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="defensive_iq",
        ),
        migrations.RemoveField(
            model_name="player",
            name="dribbling",
        ),
        migrations.RemoveField(
            model_name="player",
            name="dunking",
        ),
        migrations.RemoveField(
            model_name="player",
            name="endurance",
        ),
        migrations.RemoveField(
            model_name="player",
            name="height",
        ),
        migrations.RemoveField(
            model_name="player",
            name="jumping",
        ),
        migrations.RemoveField(
            model_name="player",
            name="low_post_scoring",
        ),
        migrations.RemoveField(
            model_name="player",
            name="offensive_iq",
        ),
        migrations.RemoveField(
            model_name="player",
            name="point_jump_shot_ability",
        ),
        migrations.RemoveField(
            model_name="player",
            name="rebounding",
        ),
        migrations.RemoveField(
            model_name="player",
            name="speed",
        ),
        migrations.RemoveField(
            model_name="player",
            name="strength",
        ),
        migrations.AddField(
            model_name="player",
            name="apg",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Assists per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="basketball_iq",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="bpg",
            field=models.DecimalField(
                decimal_places=10, help_text="Blocks per game", max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="coachability",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="defensive_rebounding",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="drpg",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Defensive rebounds per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="fg",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Field goals per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="fg_pct",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Field goal percentage",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="fga",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Field goal attempts per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="fpg",
            field=models.DecimalField(
                decimal_places=10, help_text="Fouls per game", max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="ft",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Free throws per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="ft_pct",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Free throw percentage",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="fta",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Free throw attempts per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="g",
            field=models.DecimalField(
                decimal_places=10, help_text="Games played", max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="hustle",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="interior_defense",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="interior_shooting",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="leadership",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="longevity",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="mid_range_shooting",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="offensive_rebounding",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="orpg",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Offensive rebounds per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="perimeter_defense",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="physicality",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="ppg",
            field=models.DecimalField(
                decimal_places=10, help_text="Points per game", max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="rpg",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Rebounds per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="spg",
            field=models.DecimalField(
                decimal_places=10, help_text="Steals per game", max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="three_p",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Three pointers per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="three_p_pct",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Three point percentage",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="three_pa",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Three pointer attempts per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="tpg",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Turnovers per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="two_p",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Two pointers per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="two_p_pct",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Two point percentage",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="two_pa",
            field=models.DecimalField(
                decimal_places=10,
                help_text="Two pointer attempts per game",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date updated"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="free_throw_shooting",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="passing",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="three_point_shooting",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
