# Generated by Django 4.0.5 on 2022-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulator",
            "0004_remove_player_defensive_iq_remove_player_dribbling_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="accessory",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="dna",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="exo_shell",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="face",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="finger_tips",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gin_backgrounds",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gin_basketball",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gin_internals",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gin_jersey",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gin_jersey_trim",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="hair",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="side_shield",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
