# Generated by Django 4.0.5 on 2022-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0005_player_accessory_player_dna_player_exo_shell_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="dna",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gin_backgrounds",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gin_basketball",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gin_internals",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gin_jersey",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gin_jersey_trim",
        ),
        migrations.RemoveField(
            model_name="player",
            name="side_shield",
        ),
        migrations.AddField(
            model_name="player",
            name="background",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="balls",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="ear_plate",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="guts",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="jersey",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="jersey_trim",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
