# Generated by Django 4.0.5 on 2022-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0006_remove_player_dna_remove_player_gin_backgrounds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="basketball_iq",
        ),
        migrations.RemoveField(
            model_name="player",
            name="coachability",
        ),
        migrations.RemoveField(
            model_name="player",
            name="defensive_rebounding",
        ),
        migrations.RemoveField(
            model_name="player",
            name="free_throw_shooting",
        ),
        migrations.RemoveField(
            model_name="player",
            name="hustle",
        ),
        migrations.RemoveField(
            model_name="player",
            name="interior_defense",
        ),
        migrations.RemoveField(
            model_name="player",
            name="interior_shooting",
        ),
        migrations.RemoveField(
            model_name="player",
            name="leadership",
        ),
        migrations.RemoveField(
            model_name="player",
            name="longevity",
        ),
        migrations.RemoveField(
            model_name="player",
            name="mid_range_shooting",
        ),
        migrations.RemoveField(
            model_name="player",
            name="offensive_rebounding",
        ),
        migrations.RemoveField(
            model_name="player",
            name="passing",
        ),
        migrations.RemoveField(
            model_name="player",
            name="perimeter_defense",
        ),
        migrations.RemoveField(
            model_name="player",
            name="physicality",
        ),
        migrations.RemoveField(
            model_name="player",
            name="three_point_shooting",
        ),
        migrations.RemoveField(
            model_name="player",
            name="top_attributes_1",
        ),
        migrations.RemoveField(
            model_name="player",
            name="top_attributes_2",
        ),
        migrations.RemoveField(
            model_name="player",
            name="top_attributes_3",
        ),
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="ast_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="bball_iq_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="coachability_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="drb_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="ft_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="hustle_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="interior_2pt_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="interior_defense_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="leadership_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="longevity_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="midrange_2pt_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="orb_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="perimeter_defense_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="physicality_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="star_rating",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="three_pt_rating",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="top_attribute_1",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="top_attribute_2",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="top_attribute_3",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
