# Generated by Django 4.0.5 on 2022-09-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0007_remove_player_basketball_iq_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position_1",
            field=models.CharField(
                choices=[("G", "Guard"), ("F", "Forward"), ("C", "Center")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="position_2",
            field=models.CharField(
                choices=[("G", "Guard"), ("F", "Forward"), ("C", "Center")],
                max_length=20,
                null=True,
            ),
        ),
    ]
