# Generated by Django 4.0.5 on 2022-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0008_alter_player_position_1_alter_player_position_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="top_attribute_1",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("three_pt_rating", "Three Point Shooting"),
                    ("interior_2pt_rating", "Interior Two Point Shooting"),
                    ("midrange_2pt_rating", "Midrange Two Point Shooting"),
                    ("ft_rating", "Free Throw Shooting"),
                    ("drb_rating", "Defensive Rebound"),
                    ("orb_rating", "Offensive Rebound"),
                    ("ast_rating", "Passing"),
                    ("physicality_rating", "Physicality"),
                    ("interior_defense_rating", "Interior Defense"),
                    ("perimeter_defense_rating", "Perimeter Defense"),
                    ("longevity_rating", "Longevity"),
                    ("hustle_rating", "Hustle"),
                    ("bball_iq_rating", "Basketball IQ"),
                    ("leadership_rating", "Leadership"),
                    ("coachability_rating", "Coachability"),
                ],
                default="",
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="top_attribute_2",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("three_pt_rating", "Three Point Shooting"),
                    ("interior_2pt_rating", "Interior Two Point Shooting"),
                    ("midrange_2pt_rating", "Midrange Two Point Shooting"),
                    ("ft_rating", "Free Throw Shooting"),
                    ("drb_rating", "Defensive Rebound"),
                    ("orb_rating", "Offensive Rebound"),
                    ("ast_rating", "Passing"),
                    ("physicality_rating", "Physicality"),
                    ("interior_defense_rating", "Interior Defense"),
                    ("perimeter_defense_rating", "Perimeter Defense"),
                    ("longevity_rating", "Longevity"),
                    ("hustle_rating", "Hustle"),
                    ("bball_iq_rating", "Basketball IQ"),
                    ("leadership_rating", "Leadership"),
                    ("coachability_rating", "Coachability"),
                ],
                default="",
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="top_attribute_3",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("three_pt_rating", "Three Point Shooting"),
                    ("interior_2pt_rating", "Interior Two Point Shooting"),
                    ("midrange_2pt_rating", "Midrange Two Point Shooting"),
                    ("ft_rating", "Free Throw Shooting"),
                    ("drb_rating", "Defensive Rebound"),
                    ("orb_rating", "Offensive Rebound"),
                    ("ast_rating", "Passing"),
                    ("physicality_rating", "Physicality"),
                    ("interior_defense_rating", "Interior Defense"),
                    ("perimeter_defense_rating", "Perimeter Defense"),
                    ("longevity_rating", "Longevity"),
                    ("hustle_rating", "Hustle"),
                    ("bball_iq_rating", "Basketball IQ"),
                    ("leadership_rating", "Leadership"),
                    ("coachability_rating", "Coachability"),
                ],
                default="",
                max_length=35,
            ),
        ),
    ]
