# Generated by Django 4.0.5 on 2022-10-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0009_alter_player_top_attribute_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="last_name",
        ),
        migrations.AddField(
            model_name="player",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
