# Generated by Django 4.0.5 on 2022-10-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0010_remove_player_first_name_remove_player_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="image_url",
        ),
        migrations.AddField(
            model_name="player",
            name="canonical",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
