# Generated by Django 4.0.5 on 2022-11-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0011_remove_player_image_url_player_canonical"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayByPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed", models.TextField(null=True)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="play_by_play",
                        to="simulator.simulation",
                    ),
                ),
            ],
        ),
    ]
