# Generated by Django 4.0.5 on 2022-11-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0012_playbyplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="ensemble",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
