# Generated by Django 4.0.5 on 2022-11-28 20:57

from django.db import migrations, models

import simulator.models


def update_simulation_status_labels(apps, schema_editor):
    Simulation = apps.get_model("simulator", "Simulation")
    for simulation in Simulation.objects.all():
        if simulation.status == "N":
            simulation.status = simulator.models.Simulation.Status.NOT_CREATED
        if simulation.status == "P":
            simulation.status = simulator.models.Simulation.Status.PENDING
        if simulation.status == "S":
            simulation.status = simulator.models.Simulation.Status.STARTED
        if simulation.status == "F":
            simulation.status = simulator.models.Simulation.Status.FINISHED
        if simulation.status == "E":
            simulation.status = simulator.models.Simulation.Status.ERRORED
        if simulation.status == "T":
            simulation.status = simulator.models.Simulation.Status.TIMED_OUT

        simulation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0013_player_ensemble"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT CREATED", "Not Created"),
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("FINISHED", "Finished"),
                    ("ERRORED", "Errored"),
                    ("TERMINAL ERROR", "Terminal Error"),
                    ("TIMED OUT", "Timed Out"),
                ],
                default="NOT CREATED",
                max_length=14,
            ),
        ),
        migrations.RunPython(update_simulation_status_labels),
    ]
