# Generated by Django 4.0.5 on 2023-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0014_alter_simulation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_playable",
            field=models.BooleanField(default=True),
        ),
    ]
