# Generated by Django 4.0.5 on 2023-05-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0015_player_is_playable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="uuid",
            field=models.UUIDField(
                help_text="The simulator UUID if successfully created",
                null=True,
                unique=True,
            ),
        ),
    ]
