# Generated by Django 4.0.5 on 2023-05-25 05:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0016_alter_simulation_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerGameStats",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("won", models.BooleanField()),
                (
                    "fg",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Field goals",
                    ),
                ),
                (
                    "ft",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Free throws",
                    ),
                ),
                (
                    "pf",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, null=True, verbose_name="Pf"
                    ),
                ),
                (
                    "ast",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Assists",
                    ),
                ),
                (
                    "blk",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Blocks",
                    ),
                ),
                (
                    "drb",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Defensive rebounds",
                    ),
                ),
                (
                    "fga",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Field goal attempts",
                    ),
                ),
                (
                    "fta",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Free throw attempts",
                    ),
                ),
                (
                    "orb",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Offensive rebounds",
                    ),
                ),
                (
                    "pts",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Points",
                    ),
                ),
                (
                    "stl",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Steals",
                    ),
                ),
                (
                    "tov",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Turnovers",
                    ),
                ),
                (
                    "trb",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Total rebounds",
                    ),
                ),
                (
                    "two_p",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Two pointers",
                    ),
                ),
                (
                    "fg_pct",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Fielg goals percentage",
                    ),
                ),
                (
                    "ft_pct",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Free throws percentage",
                    ),
                ),
                (
                    "two_pa",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Two pointers attempts",
                    ),
                ),
                (
                    "three_p",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Three pointers",
                    ),
                ),
                (
                    "three_pa",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Three pointers attempts",
                    ),
                ),
                (
                    "two_p_pct",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Two pointers percentage",
                    ),
                ),
                (
                    "three_p_pct",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        null=True,
                        verbose_name="Three pointers percentage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.player",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.simulation",
                        to_field="uuid",
                    ),
                ),
            ],
        ),
    ]
