# Generated by Django 4.0.5 on 2023-06-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0017_playergamestats"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=7, unique=True)),
                ("player_token", models.IntegerField(unique=True)),
                ("player_canonical", models.CharField(max_length=128, unique=True)),
                ("player_uuid", models.UUIDField(unique=True)),
                ("games", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("fg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("ft", models.DecimalField(decimal_places=10, max_digits=20)),
                ("fpg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("apg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("bpg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("drpg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("fga", models.DecimalField(decimal_places=10, max_digits=20)),
                ("fta", models.DecimalField(decimal_places=10, max_digits=20)),
                ("orpg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("ppg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("spg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("tpg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("rpg", models.DecimalField(decimal_places=10, max_digits=20)),
                ("two_p", models.DecimalField(decimal_places=10, max_digits=20)),
                ("two_pa", models.DecimalField(decimal_places=10, max_digits=20)),
                ("three_p", models.DecimalField(decimal_places=10, max_digits=20)),
                ("three_pa", models.DecimalField(decimal_places=10, max_digits=20)),
                ("fg_pct", models.DecimalField(decimal_places=10, max_digits=20)),
                ("ft_pct", models.DecimalField(decimal_places=10, max_digits=20)),
                ("two_p_pct", models.DecimalField(decimal_places=10, max_digits=20)),
                ("three_p_pct", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.player",
                    ),
                ),
            ],
        ),
    ]
