# Generated by Django 4.0.5 on 2023-06-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0018_historicalplayerstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalplayerstats",
            name="season",
            field=models.CharField(max_length=7),
        ),
    ]
