# Generated by Django 4.0.5 on 2023-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0019_alter_historicalplayerstats_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalplayerstats",
            name="fg_pct",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplayerstats",
            name="ft_pct",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplayerstats",
            name="three_p_pct",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalplayerstats",
            name="two_p_pct",
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
