# Generated by Django 4.0.5 on 2023-06-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0020_alter_historicalplayerstats_fg_pct_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="historicalplayerstats",
            unique_together={("season", "player")},
        ),
    ]
