# Generated by Django 4.0.5 on 2023-07-14 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulator",
            "0023_alltimeplayerstatsview_currentseasonplayerstatsview_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="kind",
            field=models.CharField(
                choices=[("ON_CHAIN", "On Chain"), ("OFF_CHAIN", "Off Chain")],
                default="ON_CHAIN",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="prior_tokens",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], size=None
            ),
        ),
    ]
