# Generated by Django 4.0.5 on 2023-07-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulator",
            "0023_alltimeplayerstatsview_currentseasonplayerstatsview_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentSeasonTeamSPView",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("played_today", models.IntegerField()),
                ("won_this_week", models.IntegerField()),
                ("total_sp", models.IntegerField()),
            ],
            options={
                "db_table": "view_current_season_team_sp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CurrentSeasonTeamSPViewProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.currentseasonteamspview",),
        ),
    ]
