# Generated by Django 4.0.5 on 2023-07-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0024_currentseasonteamspview_currentseasonteamspviewproxy"),
        ("simulator", "0024_player_kind_player_prior_tokens"),
    ]

    operations = []
