# Generated by Django 4.0.5 on 2023-07-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0026_player_is_taken_alter_player_prior_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="is_taken",
        ),
    ]
