# Generated by Django 4.0.5 on 2023-08-14 05:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0027_remove_player_is_taken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "three_pt_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "interior_2pt_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "midrange_2pt_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "ft_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "drb_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "orb_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "ast_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "physicality_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "interior_defense_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "perimeter_defense_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "longevity_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "hustle_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "bball_iq_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "leadership_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "coachability_delta",
                    models.DecimalField(decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "newly_revealed_ratings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.player",
                    ),
                ),
            ],
        ),
    ]
