# Generated by Django 4.0.5 on 2023-08-14 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0028_playerprogression"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprogression",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playerprogression",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date updated"
            ),
        ),
    ]
