# Generated by Django 4.0.5 on 2023-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0029_playerprogression_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprogression",
            name="season",
            field=models.CharField(default="s2", max_length=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="playerprogression",
            unique_together={("season", "player")},
        ),
    ]
