# Generated by Django 4.0.5 on 2023-08-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0030_playerprogression_season_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalplayerstats",
            name="player_token",
            field=models.IntegerField(),
        ),
    ]
