# Generated by Django 4.0.5 on 2023-08-29 21:26

from django.db import migrations, models

import simulator.model_views


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0032_alter_historicalplayerstats_player_canonical_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllTimePlayerStatsViewFiveTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "view_all_time_player_stats_5_tokens",
                "managed": False,
            },
            bases=(simulator.model_views.AllTimePlayerStatsViewMixin,),
        ),
        migrations.CreateModel(
            name="AllTimePlayerStatsViewOneToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "view_all_time_player_stats_1_token",
                "managed": False,
            },
            bases=(simulator.model_views.AllTimePlayerStatsViewMixin,),
        ),
        migrations.CreateModel(
            name="AllTimePlayerStatsViewThreeTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "view_all_time_player_stats_3_tokens",
                "managed": False,
            },
            bases=(simulator.model_views.AllTimePlayerStatsViewMixin,),
        ),
        migrations.CreateModel(
            name="CurrentSeasonPlayerStatsViewFiveTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "view_current_season_player_stats_5_tokens",
                "managed": False,
            },
            bases=(simulator.model_views.CurrentSeasonPlayerStatsViewMixin,),
        ),
        migrations.CreateModel(
            name="CurrentSeasonPlayerStatsViewOneToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "view_current_season_player_stats_1_token",
                "managed": False,
            },
            bases=(simulator.model_views.CurrentSeasonPlayerStatsViewMixin,),
        ),
        migrations.CreateModel(
            name="CurrentSeasonPlayerStatsViewThreeTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "view_current_season_player_stats_3_tokens",
                "managed": False,
            },
            bases=(simulator.model_views.CurrentSeasonPlayerStatsViewMixin,),
        ),
        migrations.CreateModel(
            name="AllTimePlayerStatsViewProxyFiveTokens",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.alltimeplayerstatsviewfivetokens",),
        ),
        migrations.CreateModel(
            name="AllTimePlayerStatsViewProxyOneToken",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.alltimeplayerstatsviewonetoken",),
        ),
        migrations.CreateModel(
            name="AllTimePlayerStatsViewProxyThreeTokens",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.alltimeplayerstatsviewthreetokens",),
        ),
        migrations.CreateModel(
            name="CurrentSeasonPlayerStatsViewProxyFiveTokens",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.currentseasonplayerstatsviewfivetokens",),
        ),
        migrations.CreateModel(
            name="CurrentSeasonPlayerStatsViewProxyOneToken",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.currentseasonplayerstatsviewonetoken",),
        ),
        migrations.CreateModel(
            name="CurrentSeasonPlayerStatsViewProxyThreeTokens",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simulator.currentseasonplayerstatsviewthreetokens",),
        ),
    ]
