# Generated by Django 4.0.6 on 2022-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_address", models.CharField(max_length=42)),
                ("from_address", models.CharField(max_length=42)),
                ("token", models.IntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
                ("log_index", models.IntegerField()),
                ("block", models.IntegerField(db_index=True)),
            ],
            options={
                "unique_together": {("tx_hash", "log_index")},
            },
        ),
    ]
