# Generated by Django 4.0.5 on 2022-11-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="to_address",
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
