# Generated by Django 4.0.5 on 2023-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eth", "0002_alter_transfer_to_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenPurchaseIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phase", models.CharField(max_length=20)),
                ("wallet_address", models.CharField(db_index=True, max_length=42)),
                ("requested_amount", models.IntegerField(default=0)),
                ("confirmed_amount", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True)),
            ],
        ),
    ]
