# Generated by Django 4.0.5 on 2023-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eth", "0003_tokenpurchaseintent"),
    ]

    def insert_default_data(apps, schema_editor):
        MintPhase = apps.get_model("eth", "MintPhase")
        new_phase = MintPhase(phase="OWNERS_ONLY")
        new_phase.save()

    operations = [
        migrations.CreateModel(
            name="MintPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phase", models.CharField(max_length=20)),
            ],
        ),
        migrations.RunPython(insert_default_data),
    ]
