enum MINT_STATES {
    CONNECTED,
    CONNECTING,
    CONNECT_ERROR,
    ERROR_CONNECTING_TO_CONTRACT,
    INSUFFICIENT_FUNDS,
    MINTING,
    MINT_IN_PROGRESS,
    NOT_IN_ALLOWLIST,
    MINT_ERROR,
    MINT_SUCCEEDED,
    NOT_ON_CORRECT_NETWORK,
    NO_METAMASK,
    NO_TOKENS_LEFT,
    QUANTITY_EXCEEDS_REMAINING_TOKENS,
    QUANTITY_EXCEEDS_REMAINING_USER_TOKENS,
    USER_TOKEN_LIMIT_REACHED,
}

export default MINT_STATES;
